[package]
authors = ["David Peter <mail@david-peter.de>"]
categories = ["command-line-utilities"]
description = "Library to read and write the LS_COLORS command line variable"
homepage = "https://github.com/sharkdp/lscolors"
license = "MIT/Apache-2.0"
name = "lscolors"
readme = "README.md"
repository = "https://github.com/sharkdp/lscolors"
version = "0.1.0"
edition = "2018"

[dependencies]
ansi_term = { version = "0.11", optional = true }

[features]
default = ["ansi_term"]

[[bin]]
name = "lscolors"
path = "src/bin.rs"
required-features = ["ansi_term"]
